### ISSUE TITLE
When should I use branches 'dev' vs 'main'?

### ISSUE THREAD

**Issue by gobengo** [elastic-ipfs/indexer-lambda#53]
How can I learn the semantics around the main 'main' branch and the 'dev' branch that I see @alanshaw PR'd into? https://github.com/ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/pull/52/files

e.g. should there be a CONTRIBUTING.md ?

**Comment by gobengo** [comment]
One question: When does 'dev' get merged into 'main', if ever?

**Comment by alanshaw** [comment]
https://github.com/ipfs-elastic-provider/ipfs-elastic-provider/blob/main/cicd-workflows.md
